### ISSUE TITLE
Building From Source on Windows 10

### ISSUE THREAD

**Issue by nopara73** [justinmoon/junction#23]
I am trying to build junction on Windows 10. This is a guide on how to do that and what blocker I find (if any.)

## Original Guide 

For reference, I copied the original Linux guide here:

Prerequisites.

* `bitcoind` on testnet
* Python 3.6 or higher

See [this tweetstorm](https://twitter.com/_JustinMoon_/status/1166905722325667841?s=20) for screenshots. They'll probably go out-of-date quickly ...

Junction project uses [HWI](https://github.com/bitcoin-core/HWI) to communicate with hardware wallets. Follow [these instructions](https://github.com/bitcoin-core/HWI#prerequisites) to install libusb dependency for HWI (don't do the `poetry install` step). If you're on Linux you may need to install udev rules.

```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
mkdir wallets
python ui.py
```

Open `localhost:5000` in your browser

## Quick Tangent: WSL

I tried and succeeded to build junction on Windows - Subsystem For Linux, but unfortunately libusb devices are [not discoverable](https://www.scivision.dev/libusb-windows-subsystem-for-linux/) from there, so that's a blocker.

## The Windows 10 Build Guide

Prerequisites.

1. [Get](https://bitcoincore.org) and run Bitcoin Core with RPC user and password set in config in server mode the `bitcoinqt` or normally `bitcoind`.
2. [Install Python 3.7](https://www.microsoft.com/en-us/p/python-37/9nj46sx7x90p)

Build and Run.

```
python3 -m venv venv
venv\Scripts\activate
pip install -r requirements.txt
mkdir wallets
python ui.py
```

Error.

The above steps are working perfectly, the only modification needed was replacing `source venv/bin/activate` with `venv\Scripts\activate` as [this stackoverflow reply](https://stackoverflow.com/questions/8921188/issue-with-virtualenv-cannot-activate) suggest. However for `python ui.py` I get this error.

```
(venv) C:\Users\user\Desktop\junction>python ui.py
Traceback (most recent call last):
  File "ui.py", line 7, in <module>
    from hwilib.devices import trezor
  File "C:\Users\user\Desktop\junction\venv\lib\site-packages\hwilib\devices\trezor.py", line 15, in <module>
    from usb1 import USBErrorNoDevice
  File "C:\Users\user\Desktop\junction\venv\lib\site-packages\usb1\__init__.py", line 61, in <module>
    from . import libusb1
  File "C:\Users\user\Desktop\junction\venv\lib\site-packages\usb1\libusb1.py", line 199, in <module>
    libusb = _loadLibrary()
  File "C:\Users\user\Desktop\junction\venv\lib\site-packages\usb1\libusb1.py", line 173, in _loadLibrary
    return dll_loader('libusb-1.0' + suffix, **loader_kw)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by nopara73** [comment]
I figured it out.

1. I had to download the "latest windows binaries" for libusb: https://libusb.info/.
2. Copy `MS64\dll\libusb-1.0.dll` to `C:\Windows\System32`. 

And it will work. I will hit it for a bit, then create a PR with the guide if everything works well.

**Comment by nopara73** [comment]
Something is still wrong. On the mainnet, I create wallet, set rpc then click "add signer". 

![image](https://user-images.githubusercontent.com/9156103/64487340-7e925980-d239-11e9-8476-1bb2cdf6e4fa.png)

Then get this error:

```
http://127.0.0.1:5000/add-signer/c2f5b203
Error: -5: Invalid descriptor
```

![image](https://user-images.githubusercontent.com/9156103/64487350-95d14700-d239-11e9-9f15-415255ab7a31.png)

**Comment by nopara73** [comment]
I tried it on the testnet and now the add signer worked properly, I received money, waited until it confirms and tried to send. (I set my coldcard to testnet, too.)

On my coldcard I ACKed the signing operation, then: `Failure, signing failed late (psbt.py:1315)`.

**Comment by nopara73** [comment]
Ok, I'm cosing this, because the original issue regarding build is resolved.

# Summary

- It's possible to build it on Windows 10 using the above steps.
- If I try to use junction on the mainnet with 1of1 multisig with coldcard it cannot do the `Add Signer` step.
- If I try to use junction on the testnet with 1of1 multisig with coldcard it cannot make coldcard sign the outgoing transaction.
